---
- name: Setup Linux Mint (Cinnamon) para desenvolvimento completo
  hosts: local
  become: yes
  roles:
    - common
    - shell
    - dev_tools
    - devops
    - desktop_apps
    - projects
    - gdrive
