#!/bin/bash
echo "Java: $(java -version 2>&1 | head -n 1)"
echo "Node: $(node -v)"
echo "Python: $(python --version)"
echo "Bat: $(bat --version 2>/dev/null || batcat --version 2>/dev/null)"
echo "Docker: $(docker --version)"
echo "K8s: $(kubectl version --client --short 2>/dev/null)"
echo "Helm: $(helm version --short 2>/dev/null)"
echo "K9s: $(k9s version 2>/dev/null | head -n 1)"
echo "Kind: $(kind version 2>/dev/null)"
echo "Flutter: $(flutter --version 2>/dev/null | head -n 1)"
