---
kubectl_version: "latest"
helm_version: "latest"
k9s_version: "latest"
kind_version: "latest"
docker_apt_release: ""
docker_mint_ubuntu_release_map:
  "22": "noble"
  "21": "jammy"
  "20": "focal"
